services:
  rails-app:
    image: mcr.microsoft.com/devcontainers/ruby:3.4-bookworm
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
    - db
    - selenium
    - catalog
    networks:
      - devnet
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devnet
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
  catalog:
    image: mcr.microsoft.com/devcontainers/ruby:3.4-bookworm
    volumes:
      - .:/workspace:cached
    ports:
      - "3001:3001"
    command: sleep infinity
    networks:
      - devnet
  logai:
    image: mcr.microsoft.com/devcontainers/python:3.10-bookworm
    volumes:
      - .:/workspace:cached
    ports:
      - "8050:8050"
    command: sleep infinity
volumes:
  postgres-data:

networks:
  devnet:
    