services:
  rails-app:
    image: mcr.microsoft.com/devcontainers/ruby:3.3-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
    - selenium
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
  logai:
    image: mcr.microsoft.com/devcontainers/python:3.10-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    ports:
      - "8050:8050"
      - "5000:5000"
    command: sleep infinity
    