require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/healer/error_events", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Healer::ErrorEvent. As you add validations to Healer::ErrorEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Healer::ErrorEvent.create! valid_attributes
      get healer_error_events_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      error_event = Healer::ErrorEvent.create! valid_attributes
      get healer_error_event_url(error_event)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_healer_error_event_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      error_event = Healer::ErrorEvent.create! valid_attributes
      get edit_healer_error_event_url(error_event)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Healer::ErrorEvent" do
        expect {
          post healer_error_events_url, params: { healer_error_event: valid_attributes }
        }.to change(Healer::ErrorEvent, :count).by(1)
      end

      it "redirects to the created healer_error_event" do
        post healer_error_events_url, params: { healer_error_event: valid_attributes }
        expect(response).to redirect_to(healer_error_event_url(Healer::ErrorEvent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Healer::ErrorEvent" do
        expect {
          post healer_error_events_url, params: { healer_error_event: invalid_attributes }
        }.to change(Healer::ErrorEvent, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post healer_error_events_url, params: { healer_error_event: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested healer_error_event" do
        error_event = Healer::ErrorEvent.create! valid_attributes
        patch healer_error_event_url(error_event), params: { healer_error_event: new_attributes }
        error_event.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the healer_error_event" do
        error_event = Healer::ErrorEvent.create! valid_attributes
        patch healer_error_event_url(error_event), params: { healer_error_event: new_attributes }
        error_event.reload
        expect(response).to redirect_to(healer_error_event_url(error_event))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        error_event = Healer::ErrorEvent.create! valid_attributes
        patch healer_error_event_url(error_event), params: { healer_error_event: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested healer_error_event" do
      error_event = Healer::ErrorEvent.create! valid_attributes
      expect {
        delete healer_error_event_url(error_event)
      }.to change(Healer::ErrorEvent, :count).by(-1)
    end

    it "redirects to the healer_error_events list" do
      error_event = Healer::ErrorEvent.create! valid_attributes
      delete healer_error_event_url(error_event)
      expect(response).to redirect_to(healer_error_events_url)
    end
  end
end
